version: "2.3"

services:
    mongo_grpc_service_template-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/mongo_grpc_service_template/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/mongo_grpc_service_template:rw
        ports:
          - 8080:8080
        working_dir: /mongo_grpc_service_template
        entrypoint:
          - ./tests/run_as_user.sh
