worker-threads: 4
worker-fs-threads: 2
worker-grpc-threads: 2
logger-level: info

is_testing: false

server-port: 8080
server-grpc-port: 8081

hello-endpoint: '[::1]:8081'

dbconnection: 'mongodb://localhost:27017/admin'
